# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Jaden
middle_name:
last_name: Park
email: jaden.park@wisc.edu
description:
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords:
lang: en
icon: ⚛️ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://jadenpark0.github.io
baseurl: # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: true
impressum_path:
back_to_top: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: false

# Dimensions
max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false
og_image:

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: jadenpark0
scholar_userid: VjYDiekAAAAJ
x_username: _jadenpark
linkedin_username: jaden-park-aa19a1192

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /:collection/:title/
  experiences:
    defaults:
      layout: post
    output: true
    permalink: /:collection/:title/

announcements:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 news items
  limit: # leave blank to include all the news in the `_news` folder

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - vendor
keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

imagemagick:
  enabled: false

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: Park*
  first_name: J.

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

enable_publication_badges:
  altmetric: true
  dimensions: true
  google_scholar: true
  inspirehep: true

filtered_bibtex_keywords:
  [
    abbr,
    abstract,
    additional_info,
    altmetric,
    annotation,
    arxiv,
    award,
    award_name,
    bibtex_show,
    blog,
    code,
    google_scholar_id,
    html,
    inspirehep_id,
    pdf,
    poster,
    preview,
    selected,
    slides,
    supp,
    video,
    website,
  ]

max_author_limit:
more_authors_animation_delay: 10
enable_publication_thumbnails: true

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

# -----------------------------------------------------------------------------
# Image options
# -----------------------------------------------------------------------------

lazy_loading_images: true

# -----------------------------------------------------------------------------
# Feature flags
# -----------------------------------------------------------------------------

enable_masonry: true
enable_math: true
enable_darkmode: true
enable_navbar_social: true
enable_medium_zoom: true
enable_progressbar: true

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

third_party_libraries:
  download: false
  google_fonts:
    url:
      fonts: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons&display=swap"
  imagesloaded:
    integrity:
      js: "sha256-htrLFfZJ6v5udOG+3kNLINIKh2gvoKqwEhHYfTTMICc="
    url:
      js: https://cdn.jsdelivr.net/npm/imagesloaded@{{version}}/imagesloaded.pkgd.min.js
    version: "5.0.0"
  jquery:
    integrity:
      js: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@{{version}}/dist/jquery.min.js"
    version: "3.6.0"
  mathjax:
    integrity:
      js: "sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI="
    local:
      fonts: "output/chtml/fonts/woff-v2/"
    url:
      fonts: "https://cdn.jsdelivr.net/npm/mathjax@{{version}}/es5/output/chtml/fonts/woff-v2/"
      js: "https://cdn.jsdelivr.net/npm/mathjax@{{version}}/es5/tex-mml-chtml.js"
    version: "3.2.2"
  masonry:
    integrity:
      js: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
    url:
      js: "https://cdn.jsdelivr.net/npm/masonry-layout@{{version}}/dist/masonry.pkgd.min.js"
    version: "4.2.2"
  mdb:
    integrity:
      css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
      js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
    url:
      css: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css"
      js: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js"
    version: "4.20.0"
  medium_zoom:
    integrity:
      js: "sha256-ZgMyDAIYDYGxbcpJcfUnYwNevG/xi9OHKaR/8GK+jWc="
    url:
      js: "https://cdn.jsdelivr.net/npm/medium-zoom@{{version}}/dist/medium-zoom.min.js"
    version: "1.1.0"
  polyfill:
    url:
      js: "https://cdnjs.cloudflare.com/polyfill/v{{version}}/polyfill.min.js?features=es6"
    version: "3"
