name: Check for broken links

on:
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/prettier.yml"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/prettier.yml"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: |
            --user-agent 'curl/7.54'
            --root-dir "$GITHUB_WORKSPACE"
            --exclude-path README.md
            --exclude-path _pages/404.md
            --accept '200,403,429'
            --exclude 'doi\.org/10\.1145/3799902\.3811186'
            --exclude 'github\.com/adobe-research/obj-and-mat-selection'
            --verbose
            --no-progress
            './**/*.md'
            './**/*.html'
